### ISSUE TITLE
Users Cannot login 

### ISSUE THREAD

**Issue by ItsSiamHossain** [themaruf/epbAppBugs#10]
### Steps
---
1. Open EasyPOS BD app
2. Enter demo email - demo@easyposbd.com
3. Enter password - 123456
4. Click on Sign-in (Forward) icon 

### URL
---
Not available 

### Test Inputs
---
- Entered login email.
-  Entered login password.

### Test Result
---
- User can't login to demo account.
- There was an error.

### Expected Result
---
- Users can login to demo account and properly use it.

### Screenshot
---
After step 4
![Screenshot_20220630-195347__01](https://user-images.githubusercontent.com/108253590/176698902-330410bf-d8e3-4a31-8ab4-2cad58eabadb.jpg)

![Screenshot_20220630-201024__01](https://user-images.githubusercontent.com/108253590/176699153-0b3123fb-0f48-4b22-bd1f-d56a8157c28d.jpg)

**Comment by themaruf** [comment]
This issue is fixed
